kind: pipeline
type: exec
name: default

steps:
- name: build
  commands:
  - docker build -f Dockerfile.build . -t grunt
  - docker run --rm -v $PWD:/workspace grunt _scripts/build.sh
  environment:
    IMAGE_PULL_SECRETS:
      from_secret: container_pull_secrets
  when:
    event:
    - tag

- name: publish
  commands:
  - mkdir -p $HOMEPATH/.docker; echo $IMAGE_PULL_SECRETS > $HOMEPATH/.docker/config.json
  - docker run --rm
    --env OSS_ENDPOINT=$OSS_ENDPOINT
    --env OSS_ACCESS_KEY_ID=$OSS_ACCESS_KEY_ID
    --env OSS_ACCESS_KEY_SECRET=$OSS_ACCESS_KEY_SECRET
    -v $PWD:/workspace
    grunt
    python3 _scripts/storage.py build
  environment:
    OSS_ENDPOINT:
      from_secret: oss_endpoint
    OSS_ACCESS_KEY_ID:
      from_secret: oss_access_key_id
    OSS_ACCESS_KEY_SECRET:
      from_secret: oss_access_key_secret
    IMAGE_PULL_SECRETS:
      from_secret: container_pull_secrets
  when:
    event:
    - tag
