labels:
  type: exec
  platform: linux/amd64

steps:
- name: build
  image: bash
  commands:
  - podman build --build-arg CODENAME=$CODENAME -f Dockerfile.build . -t grunt
  - podman run --rm -v $PWD:/workspace grunt _scripts/build.sh
  environment:
    CODENAME:
      from_secret: codename
  when:
    event:
    - tag

- name: publish
  image: bash
  commands:
  - podman run --rm
    --env OSS_ENDPOINT=$OSS_ENDPOINT
    --env OSS_ACCESS_KEY_ID=$OSS_ACCESS_KEY_ID
    --env OSS_ACCESS_KEY_SECRET=$OSS_ACCESS_KEY_SECRET
    -v $PWD:/workspace
    grunt
    python3 _scripts/storage.py build
  environment:
    OSS_ENDPOINT:
      from_secret: oss_endpoint
    OSS_ACCESS_KEY_ID:
      from_secret: oss_access_key_id
    OSS_ACCESS_KEY_SECRET:
      from_secret: oss_access_key_secret
    CONTAINER_USERNAME:
      from_secret: container_username
    CONTAINER_PASSWORD:
      from_secret: container_password
  when:
    event:
    - tag
