ARG CODENAME
FROM registry.drycc.cc/drycc/base:${CODENAME} as build-app

ENV NODE_VERSION="22"
ENV PYTHON_VERSION="3.13"

RUN install-stack node $NODE_VERSION \
  && install-stack python $PYTHON_VERSION \
  && . init-stack \
  && npm install --global grunt-cli \
  && pip install oss2 --disable-pip-version-check --no-cache-dir 2>/dev/null

WORKDIR /workspace
